Fix bugs when run with Ruby 3.0
This resolves the error:

    ArgumentError: wrong number of arguments
    (given 1, expected 0; required keywords: body, status)